### ISSUE TITLE
Installer uploads sensitive data without consent or any notice

### ISSUE THREAD

**Issue by ztxtz** [HeyCLI/heyCLI_client#1]
File: https://github.com/HeyCLI/heyCLI_client/blob/main/heycli_client.sh#L13

This uploads the command line history of the user without any consent or prior notice. The history can contain highly sensitive information such as passwords or API tokens.

The README mentions this step is optional and that it adds context. However, from this description alone, it's not clear that the "context" is our bash history.

**Comment by abdelhadi-azouni** [comment]
Hello [ztxtz](https://github.com/ztxtz)
Thanks for opening this important issue. 
I just added a section (IMPORTANT) in the readme file to outline the sensitive data risk. 
We will soon add some tooling to help minimise potential sensitive data risk
