### ISSUE TITLE
write a better dekstop client in python or go

### ISSUE THREAD

**Issue by nhannht** [HeyCLI/heyCLI_client#2]
Thank you for the nice application.

I just read this repo code. At this stage, this repo is a bash client to fetch results from your API. Do you have any plans to rewrite it in a better language like Python/Nodejs/Go Lang? I think it would be better for distribution. If you don’t mind, I can contribute to some lines of code.

**Comment by abdelhadi-azouni** [comment]
hello [nhannht](https://github.com/nhannht)
The point of this app is to suggest/answer questions about commands for now, so it makes sense to keep it in the terminal.
Do you have a specific use case in mind for a python/go app? 
thanks!
